# Generated by Django 5.1.3 on 2024-11-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prova',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
