# Generated by Django 5.1.3 on 2024-12-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='typeOccurrence',
            field=models.CharField(choices=[('EA', 'Exposição acidental'), ('ANA', 'Acessos não autorizados'), ('PRD', 'Perda ou roubo de dispositivos'), ('PH', 'Phishing(Tentativas de obter informações sensíveis)'), ('AES', 'Ataques de engenharia social'), ('MLW', 'Malware'), ('AIA', 'Acesso interno não autorizado'), ('OT', 'Outros')], default='OT', max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(),
        ),
    ]
